import * as fs from 'fs';
import * as path from 'path';
import type BetterSqlite3 from 'better-sqlite3';

/**
 * Generates .continuum/context.md — the human-readable, per-machine memory file.
 *
 * Local-only by design: lives next to knowledge.db inside the gitignored
 * .continuum/ directory and is never committed. It is the distilled "what
 * matters about this project" view, regenerated deterministically (no LLM)
 * from session summaries at consolidation time (Stop hook / server shutdown).
 *
 * Sections whose heading contains `@manual` are preserved verbatim across
 * regenerations — the file is a living document the user may edit, not a
 * build artifact.
 */

const GENERATED_HEADER =
  '<!-- generated by Continuum — edit freely; sections marked @manual are never overwritten -->';

interface SummaryRow {
  goal: string | null;
  key_decisions: string | null;
  resume_steps: string | null;
  created_at: number;
}

interface TaskRow {
  goal: string;
  open_questions: string;
  saved_at: number;
}

function parseJson(s: string | null): string[] {
  try { return JSON.parse(s || '[]') as string[]; } catch { return []; }
}

function dateOf(epoch: number): string {
  return new Date(epoch * 1000).toISOString().slice(0, 10);
}

/** Extract sections marked @manual from an existing context.md so they survive regeneration. */
function extractManualSections(existing: string): string[] {
  const sections: string[] = [];
  const lines = existing.split('\n');
  let current: string[] | null = null;

  for (const line of lines) {
    if (/^##\s/.test(line)) {
      if (current) sections.push(current.join('\n'));
      current = /@manual/.test(line) ? [line] : null;
    } else if (current) {
      current.push(line);
    }
  }
  if (current) sections.push(current.join('\n'));
  return sections;
}

export function generateContextMd(db: BetterSqlite3.Database, contextDir: string): string | null {
  // Last 5 consolidated sessions, newest first
  const summaries = db.prepare(`
    SELECT goal, key_decisions, resume_steps, created_at
    FROM session_summaries ORDER BY created_at DESC LIMIT 5
  `).all() as SummaryRow[];

  // Open questions from recent tasks (the "gotchas" seed)
  const recentTasks = db.prepare(`
    SELECT goal, open_questions, saved_at FROM tasks
    ORDER BY saved_at DESC LIMIT 20
  `).all() as TaskRow[];

  // Directory-level activity in the last 7 days
  const touchedDirs = db.prepare(`
    SELECT path, COUNT(*) AS touches FROM touched_files
    WHERE touched_at > unixepoch() - 604800
    GROUP BY path ORDER BY touches DESC LIMIT 50
  `).all() as { path: string; touches: number }[];

  if (summaries.length === 0 && recentTasks.length === 0) return null; // nothing to say yet

  // ── Active Work: the latest session only ─────────────────────────────────
  const latest = summaries[0];
  const activeWork: string[] = [];
  if (latest?.goal) {
    activeWork.push(`- ${latest.goal}  (last session: ${dateOf(latest.created_at)})`);
    for (const step of parseJson(latest.resume_steps).slice(0, 3)) {
      activeWork.push(`  - Next: ${step}`);
    }
  }

  // ── Decisions: accumulated across summaries, deduped, dated ──────────────
  const seenDecisions = new Set<string>();
  const decisions: string[] = [];
  for (const s of summaries) {
    for (const d of parseJson(s.key_decisions)) {
      const key = d.trim().toLowerCase();
      if (seenDecisions.has(key)) continue;
      seenDecisions.add(key);
      decisions.push(`- ${d}  (${dateOf(s.created_at)})`);
    }
  }

  // ── Open Questions: from recent tasks, deduped ────────────────────────────
  const seenQ = new Set<string>();
  const questions: string[] = [];
  for (const t of recentTasks) {
    for (const q of parseJson(t.open_questions)) {
      const key = q.trim().toLowerCase();
      if (seenQ.has(key)) continue;
      seenQ.add(key);
      questions.push(`- ${q}  (${dateOf(t.saved_at)})`);
    }
  }

  // ── Recently Active Areas: collapse file touches to directories ───────────
  const dirCounts = new Map<string, number>();
  for (const { path: p, touches } of touchedDirs) {
    const dir = path.dirname(p);
    dirCounts.set(dir, (dirCounts.get(dir) ?? 0) + touches);
  }
  const areas = [...dirCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 6)
    .map(([dir, n]) => `- ${dir}  (${n} touches this week)`);

  // ── Preserve @manual sections from the existing file ──────────────────────
  const contextPath = path.join(contextDir, 'context.md');
  let manualSections: string[] = [];
  try {
    manualSections = extractManualSections(fs.readFileSync(contextPath, 'utf8'));
  } catch { /* first generation */ }

  // ── Assemble ──────────────────────────────────────────────────────────────
  const parts: string[] = [
    `# Project Context  ${GENERATED_HEADER}`,
    '',
  ];

  if (activeWork.length) parts.push('## Active Work', ...activeWork, '');
  if (decisions.length)  parts.push('## Decisions', ...decisions.slice(0, 15), '');
  if (questions.length)  parts.push('## Open Questions', ...questions.slice(0, 10), '');
  if (areas.length)      parts.push('## Recently Active Areas', ...areas, '');

  for (const section of manualSections) {
    parts.push(section.trimEnd(), '');
  }

  const content = parts.join('\n');

  try {
    fs.mkdirSync(contextDir, { recursive: true });
    fs.writeFileSync(contextPath, content, 'utf8');
  } catch {
    return null; // read-only dir — non-fatal, the DB remains the source of truth
  }

  return contextPath;
}
